
# CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

CONFIG_ZMK_SLEEP=n

# Turn on display
CONFIG_ZMK_DISPLAY=n

#Improve connection stability
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

# custom status screen (nice-view-gem)
# CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
# turn off gem animation to save battery
# CONFIG_NICE_VIEW_GEM_ANIMATION=n
