#include "../../../rgbled_adapter.conf"

CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

CONFIG_ZMK_SLEEP=n

# Enable zmk studio
CONFIG_ZMK_STUDIO=y

#Improve connection stability
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

# Enable mouse emulation on dongle-central builds
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
